NODE_PATH=$(NODE_PATH):$(HOME)/node-v6.9.4-linux-armv7l/lib/node_modules/
NODE_PATH=$(NODE_PATH):$(HOME)/node-v6.9.4-linux-armv6l/lib/node_modules/
PATH=$(PATH):$(HOME)/node-v6.9.4-linux-armv7l/bin
PATH=$(PATH):$(HOME)/node-v6.9.4-linux-armv6l/bin

run:
	sudo node app.js

