NODE_PATH:=$(HOME)/node-v6.9.4-linux-armv7l/lib/node_modules/:$(NODE_PATH)
NODE_PATH:=$(HOME)/node-v6.9.4-linux-armv6l/lib/node_modules/:$(NODE_PATH)
PATH:=$(HOME)/node-v6.9.4-linux-armv7l/bin:$(PATH)
PATH:=$(HOME)/node-v6.9.4-linux-armv6l/bin:$(PATH)

run:
	sudo env PATH="$(PATH)" NODE_PATH="$(NODE_PATH)" node app.js
