NODE_PATH=$(HOME)/node-v6.9.4-linux-armv7l/lib/node_modules/:$(HOME)/node-v6.9.4-linux-armv6l/lib/node_modules/
PATH=$(HOME)/node-v6.9.4-linux-armv7l/bin:$(HOME)/node-v6.9.4-linux-armv6l/bin

run:
	/usr/bin/env PATH=$(PATH) NODE_PATH=$(NODE_PATH) sudo node app.js

